# Generated by Django 4.0.1 on 2022-02-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spines',
            name='spine_no',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GiftSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('shopkeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.shopkeeper')),
            ],
        ),
    ]
