# Generated by Django 4.0.1 on 2022-03-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='target_achieved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='target_assign',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
