# Generated by Django 4.0.1 on 2022-02-14 15:20

from django.db import migrations
import shopkeeper.models.customManager


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', shopkeeper.models.customManager.UserManager()),
            ],
        ),
    ]
