# Generated by Django 4.0.1 on 2022-02-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_alter_order_amount_alter_order_order_upto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cutomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.customer'),
        ),
    ]
