# Generated by Django 4.0.1 on 2022-03-02 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_alter_employee_target_achieved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='amount',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='cutomer',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='previouse_order',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.customer'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_upto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='shopkeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.shopkeeper'),
        ),
        migrations.CreateModel(
            name='ProductOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('sub_total', models.IntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.orderhistory')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.product')),
            ],
        ),
    ]
