# Generated by Django 4.0.1 on 2022-02-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_alter_spines_spine_no_giftspin'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftspin',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
