# Generated by Django 4.0.1 on 2022-03-07 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_alter_orderhistory_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopkeeper.order'),
        ),
        migrations.AlterField(
            model_name='productorderhistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopkeeper.orderhistory'),
        ),
        migrations.AlterField(
            model_name='productorderhistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopkeeper.product'),
        ),
    ]
