# Generated by Django 4.0.1 on 2022-02-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cutomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shopkeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.shopkeeper'),
        ),
    ]
