# Generated by Django 4.0.1 on 2022-03-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0003_alter_orderhistory_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'cancelled'), ('DELIVERED', 'delivered '), ('PROCESSING', 'processing')], default='PROCESSING', max_length=12),
        ),
    ]
