# Generated by Django 4.0.1 on 2022-03-04 05:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0003_rename_amount_orderhistory_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeehistry',
            old_name='target_achieved',
            new_name='daily_achieved',
        ),
        migrations.RenameField(
            model_name='employeehistry',
            old_name='target_assign',
            new_name='daily_target',
        ),
        migrations.RemoveField(
            model_name='employeehistry',
            name='area_designated',
        ),
        migrations.RemoveField(
            model_name='employeehistry',
            name='daily',
        ),
        migrations.RemoveField(
            model_name='employeehistry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeehistry',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeehistry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employeehistry',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='shopkeeper.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopkeeper.customer'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='shopkeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopkeeper.shopkeeper'),
        ),
        migrations.AlterField(
            model_name='productorderhistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopkeeper.orderhistory'),
        ),
        migrations.AlterField(
            model_name='productorderhistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shopkeeper.product'),
        ),
    ]
