# Generated by Django 4.0.1 on 2022-03-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0004_rename_target_achieved_employeehistry_daily_achieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
