# Generated by Django 4.0.1 on 2022-02-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0004_alter_order_cutomer_alter_order_shopkeeper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cutomer',
            new_name='customer',
        ),
    ]
