# Generated by Django 4.0.1 on 2022-02-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0004_rename_cutomer_order_customer_alter_order_shopkeeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spines',
            name='spine_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
