# Generated by Django 4.0.1 on 2022-03-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0005_alter_orderhistory_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.order'),
        ),
    ]
