# Generated by Django 4.0.1 on 2022-02-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0005_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productorder',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
    ]
