# Generated by Django 4.0.1 on 2022-02-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0006_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_upto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
