# Generated by Django 4.0.1 on 2022-02-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0006_productorder_price_productorder_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
