# Generated by Django 4.0.1 on 2022-03-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0006_alter_complaint_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaint',
            new_name='Complaints',
        ),
    ]
