# Generated by Django 4.0.1 on 2022-02-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0007_rename_amount_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
