# Generated by Django 4.0.1 on 2022-03-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0007_rename_daily_target_employeehistry_daily_target_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='shopkeeper.employee'),
        ),
    ]
