# Generated by Django 4.0.1 on 2022-03-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0008_alter_employeehistry_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='shopkeeper.employee'),
        ),
    ]
