# Generated by Django 4.0.1 on 2022-02-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0008_productorder_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
