# Generated by Django 4.0.1 on 2022-03-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0009_alter_employeehistry_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='order_date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_upto',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='shopkeeper',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopkeeper.order'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productorderhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productorderhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
