# Generated by Django 4.0.1 on 2022-02-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0009_remove_productorder_discount_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftspin',
            name='shopkeeper',
        ),
    ]
