# Generated by Django 4.0.1 on 2022-02-10 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0009_alter_order_customer_alter_order_shopkeeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
