# Generated by Django 4.0.1 on 2022-02-03 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0010_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
