# Generated by Django 4.0.1 on 2022-02-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0010_remove_giftspin_shopkeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftSpin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.giftspin')),
                ('shopkeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.shopkeeper')),
            ],
        ),
    ]
