# Generated by Django 4.0.1 on 2022-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0011_winspin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_assign', models.CharField(max_length=10, null=True)),
                ('target_achieved', models.CharField(max_length=10, null=True)),
                ('area_designated', models.CharField(blank=True, max_length=250, null=True)),
                ('daily', models.DateField()),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='r_price',
        ),
        migrations.AddField(
            model_name='product',
            name='w_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='shopkeeper_type',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('WSALE', 'Wholesale')], default='RETAIL', max_length=7),
        ),
    ]
